services:
  app:
    build: .
    container_name: enterprise_etl_app
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: enterprise_etl_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: